targets:
  $default:
    builders:
      i69n:
        options:
          default_locale: en
          locales:
            - en
            - es
            - pt
            - fr
            - de
            - it
            - ja
            - ko
            - zh
            - hi
            - id
            - tr
            - ru
            - ar
        generate_for:
          - lib/messages.i69n.yaml
          - lib/messages_*.i69n.yaml
