// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdyyMd-CbLE5YZvg243z7psLpdLyli_ZY',
    appId: '1:894286222021:web:c79a0ba0adc87cfef816ac',
    messagingSenderId: '894286222021',
    projectId: 'quietflip',
    authDomain: 'quietflip.firebaseapp.com',
    storageBucket: 'quietflip.firebasestorage.app',
    measurementId: 'G-E83V0N2P0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNjOEOAEGs195BzdNkd_dDFbJJA49y4A4',
    appId: '1:894286222021:android:fae08cb893f269f6f816ac',
    messagingSenderId: '894286222021',
    projectId: 'quietflip',
    storageBucket: 'quietflip.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2tEPoW3sBVzPnwDu_rkRG0ikKwrlXXos',
    appId: '1:894286222021:ios:8a3b7b5f9b964f32f816ac',
    messagingSenderId: '894286222021',
    projectId: 'quietflip',
    storageBucket: 'quietflip.firebasestorage.app',
    iosBundleId: 'live.iajaykumar.quietflip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2tEPoW3sBVzPnwDu_rkRG0ikKwrlXXos',
    appId: '1:894286222021:ios:8a3b7b5f9b964f32f816ac',
    messagingSenderId: '894286222021',
    projectId: 'quietflip',
    storageBucket: 'quietflip.firebasestorage.app',
    iosBundleId: 'live.iajaykumar.quietflip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdyyMd-CbLE5YZvg243z7psLpdLyli_ZY',
    appId: '1:894286222021:web:ab0094bda3ab8b53f816ac',
    messagingSenderId: '894286222021',
    projectId: 'quietflip',
    authDomain: 'quietflip.firebaseapp.com',
    storageBucket: 'quietflip.firebasestorage.app',
    measurementId: 'G-E8NSXPSMNW',
  );
}
